/*
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AgentsApi} from './api/AgentsApi';
import {ContractsApi} from './api/ContractsApi';
import {DefaultApi} from './api/DefaultApi';
import {FactionsApi} from './api/FactionsApi';
import {FleetApi} from './api/FleetApi';
import {SystemsApi} from './api/SystemsApi';

/**
* SpaceTraders_is_an_open_universe_game_and_learning_platform_that_offers_a_set_of_HTTP_endpoints_to_control_a_fleet_of_ships_and_explore_a_multiplayer_universe_The_API_is_documented_using__OpenAPI_httpsgithub_comSpaceTradersAPIapi_docs__You_can_send_your_first_request_right_here_in_your_browser_to_check_the_status_of_the_game_server_json_http__method_GET__url_httpsapi_spacetraders_iov2Unlike_a_traditional_game_SpaceTraders_does_not_have_a_first_party_client_or_app_to_play_the_game__Instead_you_can_use_the_API_to_build_your_own_client_write_a_script_to_automate_your_ships_or_try_an_app_built_by_the_community_We_have_a__Discord_channel_httpsdiscord_cominvitejh6zurdWk5_where_you_can_share_your_projects_ask_questions_and_get_help_from_other_players_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SpaceTradersApi = require('index'); // See note below*.
* var xxxSvc = new SpaceTradersApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SpaceTradersApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SpaceTradersApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SpaceTradersApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
    * The AgentsApi service constructor.
    * @property {module:api/AgentsApi}
    */
    AgentsApi,

    /**
    * The ContractsApi service constructor.
    * @property {module:api/ContractsApi}
    */
    ContractsApi,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The FactionsApi service constructor.
    * @property {module:api/FactionsApi}
    */
    FactionsApi,

    /**
    * The FleetApi service constructor.
    * @property {module:api/FleetApi}
    */
    FleetApi,

    /**
    * The SystemsApi service constructor.
    * @property {module:api/SystemsApi}
    */
    SystemsApi
};
